Rails.application.config.assets.precompile += %w( gmaps4rails.js )
Rails.application.config.assets.precompile += %w( points.js )
Rails.application.config.assets.precompile += %w( ckeditor/* )
Rails.application.config.assets.precompile += %w( gmaps4rails.css)
Rails.application.config.assets.precompile += %w( map.css)